name: Azure App from container

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: project7.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build . -t project7.azurecr.io/gitcontainer:${{ github.sha }}
        docker push project7.azurecr.io/gitcontainer:${{ github.sha }} 
      
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'ictproject'
        images: 'project7.azurecr.io/gitcontainer:${{ github.sha }}'
