name: CI
on: [push, pull_request]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master

        - name: 'Login via Azure CLI'
          uses: Azure/docker-login@v1
          with:
              login-server: project7.azurecr.io
              username: ${{ SECRETS.REGISTRY_USERNAME }}
              password: ${{ SECRETS.REGISTRY_PASSWORD }}

        - run: |
            docker build . -t project7.azurecr.io/gicontainer:${{ github.sha }}
            docker push project7.azurecr.io/gicontainer:${{ github.sha }}

        - name: 'Azure Login'
          uses: azure/login@v1
          with:
            creds: ${{ SECRETS.AZURE_CREDENTIALS }}
